package com.example.data.agent

import java.util.regex.Pattern

object AgentActionParser {

    /**
     * Extracts markdown code blocks from text for quick viewing, download, and execution.
     */
    fun extractCodeBlocks(text: String): List<ExtractedCodeBlock> {
        val blocks = mutableListOf<ExtractedCodeBlock>()
        val codeBlockRegex = Pattern.compile("```([a-zA-Z0-9_-]*)\\s*\\n?([\\s\\S]*?)```", Pattern.MULTILINE)
        val matcher = codeBlockRegex.matcher(text)

        while (matcher.find()) {
            val rawLang = matcher.group(1)?.trim() ?: ""
            val code = matcher.group(2) ?: ""

            var detectedFilename: String? = null
            var lang = rawLang.ifEmpty { "code" }

            // Check if first line in code is a filename comment like // filename: app.js or /* filename: style.css */ or <!-- filename: index.html -->
            val lines = code.trim().lines()
            if (lines.isNotEmpty()) {
                val first = lines.first().trim()
                val filenameMatcher = Pattern.compile("(?:(?:\\/\\/|#|<!--|\\/\\*)\\s*(?:file|filename|filepath):?\\s*([a-zA-Z0-9._\\-\\/]+))", Pattern.CASE_INSENSITIVE).matcher(first)
                if (filenameMatcher.find()) {
                    detectedFilename = filenameMatcher.group(1)?.trim()
                }
            }

            if (detectedFilename == null) {
                // Default filename based on language
                detectedFilename = when (lang.lowercase()) {
                    "html" -> "index.html"
                    "css" -> "style.css"
                    "javascript", "js" -> "script.js"
                    "json" -> "data.json"
                    "kotlin", "kt" -> "Main.kt"
                    "python", "py" -> "main.py"
                    "markdown", "md" -> "README.md"
                    else -> "code_${blocks.size + 1}.$lang"
                }
            }

            blocks.add(ExtractedCodeBlock(language = lang, filename = detectedFilename, code = code))
        }

        return blocks
    }

    /**
     * Extracts structured workspace actions generated by the AI agent.
     */
    fun parseWorkspaceActions(text: String): List<DragonToolAction> {
        val actions = mutableListOf<DragonToolAction>()

        // 1. Match <dragon_action ...>...</dragon_action> or self closing <dragon_action ... />
        val actionPattern = Pattern.compile("<dragon_action\\s+([^>]+)>(?:([\\s\\S]*?)<\\/dragon_action>)?|<dragon_action\\s+([^>]+)\\/>", Pattern.MULTILINE)
        val matcher = actionPattern.matcher(text)

        while (matcher.find()) {
            val attributesStr = matcher.group(1) ?: matcher.group(3) ?: ""
            val innerContent = matcher.group(2) ?: ""

            val type = extractAttribute(attributesStr, "type") ?: extractAttribute(attributesStr, "action") ?: "create_file"
            val path = extractAttribute(attributesStr, "path") ?: ""
            val source = extractAttribute(attributesStr, "source") ?: ""
            val destination = extractAttribute(attributesStr, "destination") ?: ""

            when (type.lowercase()) {
                "create_file", "write_file", "create" -> {
                    actions.add(DragonToolAction(
                        actionType = DragonToolAction.ActionType.CREATE_FILE,
                        path = path,
                        content = innerContent.trim()
                    ))
                }
                "create_folder", "mkdir" -> {
                    actions.add(DragonToolAction(
                        actionType = DragonToolAction.ActionType.CREATE_FOLDER,
                        path = path
                    ))
                }
                "delete_file", "delete", "rm" -> {
                    actions.add(DragonToolAction(
                        actionType = DragonToolAction.ActionType.DELETE_FILE,
                        path = path
                    ))
                }
                "move_file", "move", "rename", "mv" -> {
                    actions.add(DragonToolAction(
                        actionType = DragonToolAction.ActionType.MOVE_FILE,
                        sourcePath = source,
                        destinationPath = destination
                    ))
                }
                "replace_code", "replace" -> {
                    // Extract SEARCH / REPLACE blocks
                    var target = extractAttribute(attributesStr, "target") ?: ""
                    var replacement = innerContent
                    if (innerContent.contains("<<<<<<< SEARCH") && innerContent.contains("=======") && innerContent.contains(">>>>>>>")) {
                        val searchPart = innerContent.substringAfter("<<<<<<< SEARCH").substringBefore("=======").trim()
                        val replacePart = innerContent.substringAfter("=======").substringBefore(">>>>>>>").trim()
                        target = searchPart
                        replacement = replacePart
                    }
                    actions.add(DragonToolAction(
                        actionType = DragonToolAction.ActionType.REPLACE_CODE,
                        path = path,
                        targetContent = target,
                        replacementContent = replacement
                    ))
                }
                "rewrite_file" -> {
                    actions.add(DragonToolAction(
                        actionType = DragonToolAction.ActionType.REWRITE_FILE,
                        path = path,
                        content = innerContent.trim()
                    ))
                }
            }
        }

        // 2. Also support tagged files <dragon_file path="...">...</dragon_file>
        val filePattern = Pattern.compile("<dragon_file\\s+path=\"([^\"]+)\">([\\s\\S]*?)<\\/dragon_file>", Pattern.MULTILINE)
        val fileMatcher = filePattern.matcher(text)
        while (fileMatcher.find()) {
            val path = fileMatcher.group(1) ?: ""
            val content = fileMatcher.group(2) ?: ""
            if (path.isNotBlank()) {
                actions.add(DragonToolAction(
                    actionType = DragonToolAction.ActionType.CREATE_FILE,
                    path = path,
                    content = content.trim()
                ))
            }
        }

        // 3. Fallback: If no explicit dragon tags exist, but there are markdown code blocks with recognized file names, offer to import them
        if (actions.isEmpty()) {
            val codeBlocks = extractCodeBlocks(text)
            for (block in codeBlocks) {
                if (block.filename != null && (block.filename.endsWith(".html") || block.filename.endsWith(".css") || block.filename.endsWith(".js") || block.filename.endsWith(".json") || block.filename.endsWith(".kt") || block.filename.endsWith(".py") || block.filename.endsWith(".md"))) {
                    actions.add(DragonToolAction(
                        actionType = DragonToolAction.ActionType.CREATE_FILE,
                        path = block.filename,
                        content = block.code.trim()
                    ))
                }
            }
        }

        return actions
    }

    private fun extractAttribute(attributes: String, key: String): String? {
        val pattern = Pattern.compile("$key=\"([^\"]+)\"", Pattern.CASE_INSENSITIVE)
        val matcher = pattern.matcher(attributes)
        return if (matcher.find()) matcher.group(1) else null
    }
}
